version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mixodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - "27017:27017"
